import { HeapNode } from './types';

export const heapData: HeapNode[] = [
  {
    id: 'camp-1',
    type: 'campaign',
    name: 'Thời sự Quốc tế 2026',
    description: 'Chiến dịch theo dõi tin tức thời sự quốc tế nóng nhất',
    metrics: { mentions: 58200, engagement: 7300000, sentiment: 68, childCount: 2 },
    children: [
      {
        id: 'proj-1',
        type: 'project',
        name: 'Iran Chiến tranh',
        description: 'Theo dõi phản hồi về chiến sự Iran trên mạng xã hội',
        metrics: { mentions: 42100, engagement: 5800000, sentiment: 65, childCount: 3 },
        children: [
          {
            id: 'kw-1',
            type: 'keyword',
            name: '#chientranh',
            metrics: { mentions: 18500, engagement: 3200000, sentiment: 62, childCount: 245 },
            children: [
              {
                id: 'post-1',
                type: 'post',
                platform: 'tiktok',
                author: 'baohatinh',
                name: 'Tên lửa Iran vượt phòng không Israel',
                content: 'Giây phút tên lửa Iran vượt qua lưới phòng không Israel #tinnong #chientranh #iran #israel',
                metrics: { mentions: 3652, engagement: 145300, sentiment: 58 },
                children: [
                  { id: 'cmt-1', type: 'comment', author: 'user627676255', name: 'Hồng Ngọc', content: 'Lý do gì mà 2 nước chiến tranh vậy mn. ko biết nên hỏi ạ', metrics: { engagement: 130, sentiment: 50 } },
                  { id: 'cmt-2', type: 'comment', author: 'nana1.tiktok.com1', name: 'Tina - repair paint', content: 'Nước Mỹ mượn lý do giải phóng dân Iran, Mỹ nói giải cứu dân Iran khỏi chế độ độc tài 47 năm.', metrics: { engagement: 239, sentiment: 35 } },
                  { id: 'cmt-3', type: 'comment', author: 'huong.happy95', name: 'Huong Tomi', content: 'Đấy là cách nhìn cảm tính của người Việt Nam nhé. Chiến tranh này chỉ là một cái cớ rất nhỏ để Mỹ Tạo khủng hoảng thế giới.', metrics: { engagement: 15, sentiment: 40 } },
                  { id: 'cmt-4', type: 'comment', author: 'tuanminh9374', name: '1989🍀', content: 'Nó cũng nói vậy khi muốn chiến VN', metrics: { engagement: 5, sentiment: 30 } },
                  { id: 'cmt-11', type: 'comment', author: 'nguyenvan_82', name: 'Nguyễn Văn', content: 'Cầu mong hòa bình cho người dân Iran 🙏', metrics: { engagement: 320, sentiment: 60 } },
                  { id: 'cmt-12', type: 'comment', author: 'thuytrang.2k3', name: 'Thùy Trang', content: 'Xem xong thấy sợ quá, chiến tranh khổ nhất là người dân thường', metrics: { engagement: 87, sentiment: 25 } },
                  { id: 'cmt-13', type: 'comment', author: 'ducpham.official', name: 'Đức Phạm', content: 'Video quay rõ quá, tên lửa bay như sao băng luôn', metrics: { engagement: 45, sentiment: 55 } },
                ],
              },
              {
                id: 'post-2',
                type: 'post',
                platform: 'tiktok',
                author: 'vutrunews.official',
                name: 'Iran đi vào lịch sử',
                content: 'Iran chính thức đi vào lịch sử, khi một mình vã 15 nước trong 1 ngày tuyên bố không đàm phán với Mỹ #iran #israel #war',
                metrics: { mentions: 637, engagement: 89900, sentiment: 60 },
                children: [
                  { id: 'cmt-5', type: 'comment', author: 'dyfdjy9jqyhm', name: 'Yêu Nước online ❤ 🇻🇳', content: 'Mỹ chỉ ăn hiếp nước nhỏ thôi', metrics: { engagement: 15, sentiment: 28 } },
                  { id: 'cmt-6', type: 'comment', author: 'binhiuai13', name: 'Bynhh🍦', content: 'Nhi hát 50k nhạc thôi là tụi nớ hết chiến tranh vì quá hay', metrics: { engagement: 0, sentiment: 70 } },
                  { id: 'cmt-14', type: 'comment', author: 'hoangminh.99', name: 'Hoàng Minh', content: 'Iran cứng cựa thật sự, respect 🫡', metrics: { engagement: 210, sentiment: 72 } },
                  { id: 'cmt-15', type: 'comment', author: 'linhchi_sg', name: 'Linh Chi SG', content: 'Đọc tin mà thấy lo cho thế giới quá, bao giờ mới hết chiến tranh', metrics: { engagement: 56, sentiment: 30 } },
                  { id: 'cmt-16', type: 'comment', author: 'bachkhoa.2002', name: 'Bách Khoa', content: 'Phân tích rất hay, cảm ơn admin đã cập nhật nhanh', metrics: { engagement: 33, sentiment: 80 } },
                ],
              },
              {
                id: 'post-3',
                type: 'post',
                platform: 'tiktok',
                author: 'tintucchinhtriquansu',
                name: 'Cuộc chiến Mỹ với Iran',
                content: 'CUỘC CHIẾN MỸ VỚI IRAN ĐÃ BẮT ĐẦU #thoisu #thoisu24h #tintuc24h #tinnong',
                metrics: { mentions: 29, engagement: 2396, sentiment: 55 },
                children: [
                  { id: 'cmt-17', type: 'comment', author: 'thanhnien.tre', name: 'Thanh Niên Trẻ', content: 'Ai hiểu rõ tình hình giải thích giúp em với ạ', metrics: { engagement: 12, sentiment: 50 } },
                  { id: 'cmt-18', type: 'comment', author: 'minhtuan_hn', name: 'Minh Tuấn HN', content: 'Mong Việt Nam mãi hòa bình 🇻🇳', metrics: { engagement: 450, sentiment: 65 } },
                ],
              },
              {
                id: 'post-4',
                type: 'post',
                platform: 'tiktok',
                author: 'plxh.vn',
                name: 'Tên lửa Iran qua mặt đánh chặn',
                content: 'Khoảnh khắc tên lửa Iran qua mặt hơn 10 tên lửa đánh chặn #tintuc #tinnong #tinthegioi #chientranh',
                metrics: { mentions: 420, engagement: 35200, sentiment: 52 },
                children: [
                  { id: 'cmt-19', type: 'comment', author: 'khanhduy.98', name: 'Khánh Duy', content: 'Công nghệ quân sự Iran phát triển quá, vượt qua cả hệ thống Iron Dome', metrics: { engagement: 78, sentiment: 60 } },
                  { id: 'cmt-20', type: 'comment', author: 'ngocoanh_95', name: 'Ngọc Oanh', content: 'Xem mà nổi da gà, may mà mình sống ở nước hòa bình', metrics: { engagement: 25, sentiment: 40 } },
                ],
              },
              {
                id: 'post-22',
                type: 'post',
                platform: 'facebook',
                author: 'BBC Tiếng Việt',
                name: 'Phân tích chiến sự Iran-Israel',
                content: 'Phân tích toàn diện cuộc xung đột Iran-Israel: Nguyên nhân, diễn biến và hậu quả #chientranh #iran #israel #phantich',
                metrics: { mentions: 5200, engagement: 230000, sentiment: 55 },
                children: [
                  { id: 'cmt-21', type: 'comment', author: 'professor.nguyen', name: 'GS. Nguyễn Văn An', content: 'Bài viết phân tích rất chuyên sâu, cảm ơn BBC đã đưa tin khách quan', metrics: { engagement: 890, sentiment: 82 } },
                  { id: 'cmt-22', type: 'comment', author: 'haivan_tphcm', name: 'Hải Vân', content: 'Cuộc chiến proxy giữa các cường quốc, dân thường chịu thiệt nhất', metrics: { engagement: 156, sentiment: 32 } },
                  { id: 'cmt-23', type: 'comment', author: 'anhtu.law', name: 'Anh Tú - Luật sư', content: 'Theo luật quốc tế thì cả hai bên đều vi phạm nghiêm trọng', metrics: { engagement: 234, sentiment: 45 } },
                ],
              },
              {
                id: 'post-23',
                type: 'post',
                platform: 'youtube',
                author: 'RapNewsPlus',
                name: 'Tổng hợp chiến sự tuần qua',
                content: 'TỔNG HỢP CHIẾN SỰ IRAN - ISRAEL TUẦN QUA: Những diễn biến nóng nhất #chientranh #thoisu',
                metrics: { mentions: 1890, engagement: 67000, sentiment: 50 },
                children: [
                  { id: 'cmt-24', type: 'comment', author: 'quocbao_yt', name: 'Quốc Bảo', content: 'Kênh luôn cập nhật nhanh nhất, sub rồi ạ', metrics: { engagement: 45, sentiment: 85 } },
                  { id: 'cmt-25', type: 'comment', author: 'dienbienphu1954', name: 'Lịch sử VN', content: 'Lịch sử lặp lại, chỉ khác bối cảnh và công nghệ thôi', metrics: { engagement: 120, sentiment: 42 } },
                ],
              },
              {
                id: 'post-24',
                type: 'post',
                platform: 'facebook',
                author: 'VnExpress',
                name: 'Infographic chiến sự Iran',
                content: 'INFOGRAPHIC: Toàn cảnh xung đột Iran sau 30 ngày - Thiệt hại hai bên #chientranh #iran #infographic',
                metrics: { mentions: 8900, engagement: 312000, sentiment: 48 },
                children: [
                  { id: 'cmt-26', type: 'comment', author: 'datascience.vn', name: 'Data Science VN', content: 'Infographic rất trực quan, dễ hiểu. Số liệu thiệt hại kinh hoàng', metrics: { engagement: 67, sentiment: 55 } },
                  { id: 'cmt-27', type: 'comment', author: 'mama.2kids', name: 'Mẹ 2 con', content: 'Nhìn số liệu trẻ em thương vong mà đau lòng quá 😢', metrics: { engagement: 340, sentiment: 15 } },
                  { id: 'cmt-28', type: 'comment', author: 'trader.forex.vn', name: 'Trader VN', content: 'Chiến tranh leo thang thì giá dầu và vàng sẽ tiếp tục tăng', metrics: { engagement: 89, sentiment: 50 } },
                  { id: 'cmt-29', type: 'comment', author: 'hocsinh.12a', name: 'HS 12A', content: 'Cho em hỏi cuộc chiến này có liên quan gì đến cuộc chiến vùng Vịnh không ạ?', metrics: { engagement: 23, sentiment: 50 } },
                ],
              },
            ],
          },
          {
            id: 'kw-2',
            type: 'keyword',
            name: 'chien su o iran',
            metrics: { mentions: 12800, engagement: 1450000, sentiment: 64, childCount: 156 },
            children: [
              {
                id: 'post-5',
                type: 'post',
                platform: 'tiktok',
                author: 'toancanh60s',
                name: 'Cập nhật chiến sự Trung Đông',
                content: 'Cập nhật tình hình chiến sự tại Trung Đông. Thời sự sáng 05.00 ngày 05/3/2026 #chientranh #iran',
                metrics: { mentions: 15, engagement: 329, sentiment: 60 },
                children: [
                  { id: 'cmt-7', type: 'comment', author: 'user2261530225337', name: 'Yugioh Việt Nam Thanh', content: 'Thế giới sẽ hòa bình nếu trên trái đất còn 1 ng 🥺', metrics: { engagement: 1, sentiment: 45 } },
                  { id: 'cmt-30', type: 'comment', author: 'phuong.travel', name: 'Phương Travel', content: 'Mình vừa hủy chuyến du lịch Dubai vì lo ngại chiến sự lan rộng', metrics: { engagement: 34, sentiment: 35 } },
                ],
              },
              {
                id: 'post-25',
                type: 'post',
                platform: 'youtube',
                author: 'VTV24',
                name: 'Bản tin chiến sự Iran ngày 5/3',
                content: 'BẢN TIN CHIẾN SỰ IRAN 05/03/2026: Không quân Mỹ tấn công cơ sở hạt nhân, Iran tuyên bố trả đũa',
                metrics: { mentions: 4200, engagement: 189000, sentiment: 52 },
                children: [
                  { id: 'cmt-31', type: 'comment', author: 'hungpham.IT', name: 'Hùng Phạm IT', content: 'VTV24 luôn là nguồn tin đáng tin cậy nhất', metrics: { engagement: 234, sentiment: 78 } },
                  { id: 'cmt-32', type: 'comment', author: 'tranthimai.86', name: 'Trần Thị Mai', content: 'Cầu nguyện cho hòa bình thế giới 🕊️', metrics: { engagement: 567, sentiment: 55 } },
                  { id: 'cmt-33', type: 'comment', author: 'quansu.fan', name: 'Quân Sự Fan', content: 'Cơ sở hạt nhân bị tấn công thì hậu quả nghiêm trọng lắm, ô nhiễm phóng xạ', metrics: { engagement: 89, sentiment: 28 } },
                ],
              },
              {
                id: 'post-26',
                type: 'post',
                platform: 'facebook',
                author: 'Tuổi Trẻ Online',
                name: 'Phóng sự từ biên giới Iran',
                content: 'PHÓNG SỰ ĐẶC BIỆT: Cuộc sống người dân Iran ở vùng biên giới giữa mưa bom bão đạn',
                metrics: { mentions: 3100, engagement: 156000, sentiment: 30 },
                children: [
                  { id: 'cmt-34', type: 'comment', author: 'nguyenthanhlong', name: 'Nguyễn Thành Long', content: 'Phóng viên dũng cảm quá, cảm ơn đã đưa tin từ chiến trường', metrics: { engagement: 890, sentiment: 75 } },
                  { id: 'cmt-35', type: 'comment', author: 'hathu.nurse', name: 'Hà Thu - Y tá', content: 'Nhìn hình ảnh trẻ em bị thương mà không cầm được nước mắt', metrics: { engagement: 1230, sentiment: 15 } },
                ],
              },
              {
                id: 'post-27',
                type: 'post',
                platform: 'tiktok',
                author: 'thoisu.recap',
                name: 'Recap chiến sự Iran 1 phút',
                content: 'Tóm tắt chiến sự Iran trong 1 PHÚT ⚡ #chiensu #iran #recap #thoisu',
                metrics: { mentions: 890, engagement: 52000, sentiment: 55 },
                children: [
                  { id: 'cmt-36', type: 'comment', author: 'sinh_vien_2004', name: 'SV 2004', content: 'Format recap 1 phút hay quá, dễ nắm bắt thông tin', metrics: { engagement: 45, sentiment: 82 } },
                ],
              },
            ],
          },
          {
            id: 'kw-3',
            type: 'keyword',
            name: '#iran',
            metrics: { mentions: 8900, engagement: 980000, sentiment: 58, childCount: 189 },
            children: [
              {
                id: 'post-6',
                type: 'post',
                platform: 'tiktok',
                author: 'baohatinh',
                name: 'Iran phòng không Israel',
                content: 'Giây phút tên lửa Iran vượt qua lưới phòng không Israel',
                metrics: { mentions: 3652, engagement: 145300, sentiment: 58 },
                children: [
                  { id: 'cmt-37', type: 'comment', author: 'namsinh95', name: 'Nam Sinh 95', content: 'Tên lửa đạn đạo thì Iron Dome không chặn được đâu bạn ơi', metrics: { engagement: 67, sentiment: 55 } },
                ],
              },
              {
                id: 'post-7',
                type: 'post',
                platform: 'tiktok',
                author: 'vutrunews.official',
                name: 'Iran vs 15 nước',
                content: 'Iran chính thức đi vào lịch sử khi một mình vã 15 nước',
                metrics: { mentions: 637, engagement: 89900, sentiment: 60 },
                children: [
                  { id: 'cmt-38', type: 'comment', author: 'thinker.vn', name: 'Thinker VN', content: 'Tiêu đề hơi clickbait, thực tế phức tạp hơn nhiều', metrics: { engagement: 120, sentiment: 40 } },
                ],
              },
              {
                id: 'post-28',
                type: 'post',
                platform: 'youtube',
                author: 'GeoNews VN',
                name: 'Phân tích địa chính trị Iran',
                content: 'TẠI SAO IRAN KHÔNG SỢ MỸ? Phân tích sức mạnh quân sự và đồng minh của Iran #iran #diachinhtr',
                metrics: { mentions: 2300, engagement: 78000, sentiment: 62 },
                children: [
                  { id: 'cmt-39', type: 'comment', author: 'sinhvien.QHQT', name: 'SV Quan hệ Quốc tế', content: 'Video chất lượng, em đang viết luận văn về đề tài này', metrics: { engagement: 34, sentiment: 80 } },
                  { id: 'cmt-40', type: 'comment', author: 'onggia.60', name: 'Ông Già 60', content: 'Hồi xưa Iran cũng từng là đồng minh của Mỹ, thay đổi từ 1979', metrics: { engagement: 156, sentiment: 55 } },
                  { id: 'cmt-41', type: 'comment', author: 'reader.hanoi', name: 'Reader Hà Nội', content: 'Kênh này phân tích khách quan, không thiên vị bên nào 👍', metrics: { engagement: 89, sentiment: 85 } },
                ],
              },
              {
                id: 'post-29',
                type: 'post',
                platform: 'facebook',
                author: 'Thời Báo Kinh Tế',
                name: 'Ảnh hưởng kinh tế từ chiến sự Iran',
                content: 'Chiến sự Iran đẩy giá dầu lên mức kỷ lục, kinh tế toàn cầu chao đảo #iran #kinhtế #giadau',
                metrics: { mentions: 4500, engagement: 167000, sentiment: 38 },
                children: [
                  { id: 'cmt-42', type: 'comment', author: 'business.owner.vn', name: 'Chủ DN nhỏ', content: 'Giá xăng tăng liên tục, chi phí vận tải tăng, DN nhỏ khó sống quá', metrics: { engagement: 678, sentiment: 20 } },
                  { id: 'cmt-43', type: 'comment', author: 'economist.2k', name: 'Economist 2K', content: 'Fed chắc chắn phải điều chỉnh lãi suất nếu dầu tiếp tục tăng', metrics: { engagement: 234, sentiment: 45 } },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 'proj-2',
        type: 'project',
        name: 'Tin Tức 24h',
        description: 'Theo dõi tin tức nóng 24h trên các nền tảng',
        metrics: { mentions: 16100, engagement: 1500000, sentiment: 72, childCount: 3 },
        children: [
          {
            id: 'kw-4',
            type: 'keyword',
            name: '#tinnong24h',
            metrics: { mentions: 8200, engagement: 720000, sentiment: 70, childCount: 320 },
            children: [
              {
                id: 'post-8',
                type: 'post',
                platform: 'tiktok',
                author: 'baohatinh',
                name: 'Tin nóng quốc tế',
                content: 'Giây phút tên lửa Iran vượt qua lưới phòng không Israel #tinnong #tinnong24h',
                metrics: { mentions: 3652, engagement: 145300, sentiment: 58 },
                children: [
                  { id: 'cmt-44', type: 'comment', author: 'follow.news', name: 'Follow News', content: 'Kênh cập nhật tin nhanh nhất TikTok luôn 🔥', metrics: { engagement: 89, sentiment: 85 } },
                ],
              },
              {
                id: 'post-30',
                type: 'post',
                platform: 'tiktok',
                author: 'tinnong.24h',
                name: 'Động đất mạnh tại Nhật Bản',
                content: 'NÓNG: Động đất 7.2 độ richter tại Nhật Bản, cảnh báo sóng thần #tinnong24h #dongdat #nhatban',
                metrics: { mentions: 6700, engagement: 234000, sentiment: 35 },
                children: [
                  { id: 'cmt-45', type: 'comment', author: 'du_hoc_sinh_jp', name: 'DHS Nhật', content: 'Mình đang ở Tokyo, rung lắc mạnh lắm mọi người ơi, sợ quá 😰', metrics: { engagement: 2340, sentiment: 20 } },
                  { id: 'cmt-46', type: 'comment', author: 'geology.fan', name: 'Geology Fan', content: '7.2 richter là rất mạnh, hy vọng không có sóng thần', metrics: { engagement: 156, sentiment: 35 } },
                  { id: 'cmt-47', type: 'comment', author: 'pray4japan', name: 'Pray4Japan', content: 'Cầu nguyện cho Nhật Bản, đất nước đã quá nhiều lần chịu thiên tai 🙏', metrics: { engagement: 890, sentiment: 45 } },
                ],
              },
              {
                id: 'post-31',
                type: 'post',
                platform: 'facebook',
                author: 'Dân Trí',
                name: 'Bão lũ miền Trung 2026',
                content: 'Bão số 3 đổ bộ miền Trung: 15 người mất tích, hàng nghìn ngôi nhà bị ngập #tinnong24h #baolu #mientrung',
                metrics: { mentions: 8900, engagement: 456000, sentiment: 22 },
                children: [
                  { id: 'cmt-48', type: 'comment', author: 'nguoi.mien.trung', name: 'Người Miền Trung', content: 'Nhà mình ở Quảng Bình, nước ngập tới nóc rồi mọi người ơi 😭', metrics: { engagement: 3400, sentiment: 10 } },
                  { id: 'cmt-49', type: 'comment', author: 'volunteer.vn', name: 'Tình Nguyện VN', content: 'Ai muốn quyên góp có thể chuyển khoản vào tài khoản Hội Chữ thập đỏ', metrics: { engagement: 5600, sentiment: 70 } },
                  { id: 'cmt-50', type: 'comment', author: 'saigon.boy', name: 'Sài Gòn Boy', content: 'Năm nào miền Trung cũng chịu bão lũ, nhà nước cần có giải pháp lâu dài', metrics: { engagement: 234, sentiment: 35 } },
                  { id: 'cmt-51', type: 'comment', author: 'bac.nong.dan', name: 'Bác Nông Dân', content: 'Mùa màng mất trắng hết rồi, buồn quá', metrics: { engagement: 1200, sentiment: 12 } },
                ],
              },
            ],
          },
          {
            id: 'kw-5',
            type: 'keyword',
            name: '#tintuc24h',
            metrics: { mentions: 5400, engagement: 480000, sentiment: 72, childCount: 210 },
            children: [
              {
                id: 'post-9',
                type: 'post',
                platform: 'tiktok',
                author: 'tintucchinhtriquansu',
                name: 'Thời sự 24h',
                content: 'CUỘC CHIẾN MỸ VỚI IRAN ĐÃ BẮT ĐẦU #thoisu #tintuc24h',
                metrics: { mentions: 29, engagement: 2396, sentiment: 55 },
                children: [],
              },
              {
                id: 'post-32',
                type: 'post',
                platform: 'youtube',
                author: 'THVL',
                name: 'Tin tức 24h ngày 5/3/2026',
                content: 'TIN TỨC 24H MỚI NHẤT HÔM NAY 05/03/2026: Tổng hợp tin nóng trong nước và quốc tế #tintuc24h',
                metrics: { mentions: 1200, engagement: 34000, sentiment: 65 },
                children: [
                  { id: 'cmt-52', type: 'comment', author: 'ba.ve.huu', name: 'Ba Về Hưu', content: 'Ngày nào cũng xem THVL, tin tức rất đầy đủ', metrics: { engagement: 23, sentiment: 85 } },
                  { id: 'cmt-53', type: 'comment', author: 'tran.hong.nhung', name: 'Trần Hồng Nhung', content: 'Cảm ơn kênh đã tổng hợp tin tức, không phải đọc nhiều nơi', metrics: { engagement: 12, sentiment: 80 } },
                ],
              },
              {
                id: 'post-33',
                type: 'post',
                platform: 'tiktok',
                author: 'tinmoi.official',
                name: 'Vụ sập cầu tại Ấn Độ',
                content: 'KINH HOÀNG: Cầu treo tại Ấn Độ sập khi đang có hàng trăm người đi qua #tintuc24h #sapcau #ando',
                metrics: { mentions: 3400, engagement: 178000, sentiment: 25 },
                children: [
                  { id: 'cmt-54', type: 'comment', author: 'kts.vn', name: 'KTS Việt Nam', content: 'Cơ sở hạ tầng nhiều nước đang xuống cấp nghiêm trọng', metrics: { engagement: 67, sentiment: 40 } },
                  { id: 'cmt-55', type: 'comment', author: 'empathy.soul', name: 'Empathy Soul', content: 'Đau lòng quá, RIP các nạn nhân 🕯️', metrics: { engagement: 890, sentiment: 18 } },
                ],
              },
            ],
          },
          {
            id: 'kw-6',
            type: 'keyword',
            name: '#socialnews',
            metrics: { mentions: 4200, engagement: 350000, sentiment: 74, childCount: 95 },
            children: [
              {
                id: 'post-34',
                type: 'post',
                platform: 'tiktok',
                author: 'social.news.vn',
                name: 'Gen Z và thói quen đọc tin',
                content: 'Khảo sát: 78% Gen Z đọc tin tức trên TikTok thay vì báo truyền thống #socialnews #genz #tiktok',
                metrics: { mentions: 2100, engagement: 89000, sentiment: 72 },
                children: [
                  { id: 'cmt-56', type: 'comment', author: 'genz.2005', name: 'GenZ 2005', content: 'Đúng rồi, mình chỉ đọc tin trên TikTok thôi, báo dài quá lười đọc', metrics: { engagement: 345, sentiment: 75 } },
                  { id: 'cmt-57', type: 'comment', author: 'nha.bao.cu', name: 'Nhà Báo Cũ', content: 'Đáng lo ngại, tin TikTok thường thiếu kiểm chứng và thiên về giật gân', metrics: { engagement: 678, sentiment: 35 } },
                  { id: 'cmt-58', type: 'comment', author: 'media.student', name: 'SV Báo Chí', content: 'Đề tài luận văn của em đây, cảm ơn số liệu', metrics: { engagement: 23, sentiment: 80 } },
                ],
              },
              {
                id: 'post-35',
                type: 'post',
                platform: 'facebook',
                author: 'Zing News',
                name: 'Fake news lan tràn MXH',
                content: 'Cảnh báo: Hàng loạt tin giả về chiến sự Iran lan truyền trên MXH Việt Nam #socialnews #fakenews',
                metrics: { mentions: 4500, engagement: 123000, sentiment: 40 },
                children: [
                  { id: 'cmt-59', type: 'comment', author: 'fact.checker', name: 'Fact Checker VN', content: 'Mọi người cần kiểm tra nguồn trước khi share, đừng tiếp tay cho tin giả', metrics: { engagement: 2340, sentiment: 65 } },
                  { id: 'cmt-60', type: 'comment', author: 'hoang_mang', name: 'Hoang Mang', content: 'Giờ không biết tin nào thật tin nào giả nữa 😵‍💫', metrics: { engagement: 456, sentiment: 30 } },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'camp-2',
    type: 'campaign',
    name: 'Trending Văn hóa & Giải trí',
    description: 'Chiến dịch theo dõi xu hướng văn hóa giải trí trên TikTok',
    metrics: { mentions: 28500, engagement: 3200000, sentiment: 82, childCount: 2 },
    children: [
      {
        id: 'proj-3',
        type: 'project',
        name: 'Nhạc Việt Trending',
        description: 'Theo dõi các bài hát và xu hướng âm nhạc Việt',
        metrics: { mentions: 18900, engagement: 2100000, sentiment: 85, childCount: 3 },
        children: [
          {
            id: 'kw-7',
            type: 'keyword',
            name: '#camonnguoidathuccungtoi',
            metrics: { mentions: 8200, engagement: 920000, sentiment: 88, childCount: 180 },
            children: [
              {
                id: 'post-10',
                type: 'post',
                platform: 'tiktok',
                author: 'lamentlove',
                name: 'Cảm Ơn Người Đã Thức Cùng Tôi',
                content: 'Cảm Ơn Người Đã Thức Cùng Tôi // Phùng Khánh Linh #camonnguoidathuccungtoi #phungkhanhlinh #lyrics #fyp',
                metrics: { mentions: 35, engagement: 6178, sentiment: 92 },
                children: [
                  { id: 'cmt-8', type: 'comment', author: 'xunu.190899', name: 'Thu Huyền', content: 'Phim hay mà ít suất chiếu quá. Thêm suất chiếu nha. Cần nhiều bạn trẻ biết hơn về bộ phim này', metrics: { engagement: 73, sentiment: 85 } },
                  { id: 'cmt-9', type: 'comment', author: 'sonkhanhtieududu', name: 'sonkhanhtieududu', content: 'Vần cả tiếng anh cũng vậy', metrics: { engagement: 60, sentiment: 80 } },
                  { id: 'cmt-10', type: 'comment', author: 'duonggnek69', name: 'duonggnek69', content: 'Với tớ hoặc với nhiều người khác nó là một lời tri ân cuộc đời ❤', metrics: { engagement: 25, sentiment: 95 } },
                  { id: 'cmt-61', type: 'comment', author: 'musiclover.03', name: 'Music Lover 03', content: 'Bài này nghe hoài không chán, melody đỉnh quá', metrics: { engagement: 234, sentiment: 95 } },
                  { id: 'cmt-62', type: 'comment', author: 'guitar.cover.vn', name: 'Guitar Cover VN', content: 'Mình vừa cover bài này bằng guitar, mọi người qua nghe nhé', metrics: { engagement: 45, sentiment: 88 } },
                ],
              },
              {
                id: 'post-36',
                type: 'post',
                platform: 'tiktok',
                author: 'nhac.chill.247',
                name: 'Cover Cảm Ơn Người acoustic',
                content: 'Cover acoustic Cảm Ơn Người Đã Thức Cùng Tôi tại quán cafe nhỏ 🎵 #camonnguoidathuccungtoi #acoustic #cover',
                metrics: { mentions: 890, engagement: 45000, sentiment: 90 },
                children: [
                  { id: 'cmt-63', type: 'comment', author: 'cafe.lover', name: 'Cafe Lover', content: 'Quán cafe nào vậy bạn ơi, muốn ghé quá ☕', metrics: { engagement: 123, sentiment: 88 } },
                  { id: 'cmt-64', type: 'comment', author: 'acoustic.fan', name: 'Acoustic Fan', content: 'Giọng hát mộc mà hay hơn cả bản gốc luôn, xuất sắc!', metrics: { engagement: 567, sentiment: 95 } },
                  { id: 'cmt-65', type: 'comment', author: 'nguoi.lang.thang', name: 'Người Lang Thang', content: 'Nghe bản acoustic này lúc 2h sáng, cảm xúc khác hẳn', metrics: { engagement: 89, sentiment: 85 } },
                ],
              },
              {
                id: 'post-37',
                type: 'post',
                platform: 'youtube',
                author: 'Phùng Khánh Linh Official',
                name: 'MV Official Cảm Ơn Người Đã Thức Cùng Tôi',
                content: 'Phùng Khánh Linh - Cảm Ơn Người Đã Thức Cùng Tôi | Official Music Video #camonnguoidathuccungtoi',
                metrics: { mentions: 12000, engagement: 890000, sentiment: 92 },
                children: [
                  { id: 'cmt-66', type: 'comment', author: 'pkl.fanclub', name: 'PKL Fanclub', content: 'MV đẹp quá chị ơi, xứng đáng #1 trending 🏆', metrics: { engagement: 4500, sentiment: 98 } },
                  { id: 'cmt-67', type: 'comment', author: 'mv.reviewer', name: 'MV Reviewer', content: 'Concept MV sáng tạo, đạo diễn giỏi, PKL hát hay như mọi khi', metrics: { engagement: 2300, sentiment: 92 } },
                  { id: 'cmt-68', type: 'comment', author: 'international.fan', name: 'International Fan', content: 'Im from Korea and this song is so beautiful, love Vietnamese music! 🇰🇷❤️🇻🇳', metrics: { engagement: 6700, sentiment: 96 } },
                  { id: 'cmt-69', type: 'comment', author: 'nha.san.xuat', name: 'Producer VN', content: 'Production quality rất cao, âm thanh mix chuẩn quốc tế', metrics: { engagement: 890, sentiment: 90 } },
                ],
              },
            ],
          },
          {
            id: 'kw-8',
            type: 'keyword',
            name: '#phungkhanhlinh',
            metrics: { mentions: 6500, engagement: 680000, sentiment: 86, childCount: 120 },
            children: [
              {
                id: 'post-11',
                type: 'post',
                platform: 'tiktok',
                author: 'lamentlove',
                name: 'Lyrics PKL',
                content: 'Cảm Ơn Người Đã Thức Cùng Tôi // Phùng Khánh Linh',
                metrics: { mentions: 35, engagement: 6178, sentiment: 92 },
                children: [
                  { id: 'cmt-70', type: 'comment', author: 'lyrics.vn', name: 'Lyrics VN', content: 'Lời bài hát sâu lắng quá, PKL viết nhạc quá giỏi', metrics: { engagement: 56, sentiment: 90 } },
                ],
              },
              {
                id: 'post-12',
                type: 'post',
                platform: 'youtube',
                author: 'MusicVN',
                name: 'PKL MV reaction',
                content: 'Reaction MV Phùng Khánh Linh mới nhất',
                metrics: { mentions: 1200, engagement: 8500, sentiment: 88 },
                children: [
                  { id: 'cmt-71', type: 'comment', author: 'reaction.addict', name: 'Reaction Addict', content: 'Reaction chân thật nhất mình từng xem, không giả trân', metrics: { engagement: 123, sentiment: 85 } },
                  { id: 'cmt-72', type: 'comment', author: 'pkl.stan', name: 'PKL Stan', content: 'PKL xứng đáng được nhiều người biết đến hơn nữa ❤', metrics: { engagement: 345, sentiment: 95 } },
                ],
              },
              {
                id: 'post-38',
                type: 'post',
                platform: 'tiktok',
                author: 'concert.review',
                name: 'Concert PKL tại Hà Nội',
                content: 'Phùng Khánh Linh concert "Ngày Đẹp Trời" tại Hà Nội - CHÁY VÉ sau 2 phút! #phungkhanhlinh #concert #hanoi',
                metrics: { mentions: 4500, engagement: 230000, sentiment: 95 },
                children: [
                  { id: 'cmt-73', type: 'comment', author: 'fan.ha.noi', name: 'Fan Hà Nội', content: 'Mua được vé rồi, hạnh phúc quá trời 🎉', metrics: { engagement: 890, sentiment: 98 } },
                  { id: 'cmt-74', type: 'comment', author: 'het.ve', name: 'Hết Vé', content: 'F5 liên tục mà vẫn không mua được vé, buồn 😭', metrics: { engagement: 2300, sentiment: 20 } },
                  { id: 'cmt-75', type: 'comment', author: 'event.planner', name: 'Event Planner', content: 'PKL nên thêm đêm diễn, demand quá lớn', metrics: { engagement: 567, sentiment: 80 } },
                ],
              },
            ],
          },
          {
            id: 'kw-9',
            type: 'keyword',
            name: '#lyrics',
            metrics: { mentions: 4200, engagement: 380000, sentiment: 82, childCount: 95 },
            children: [
              {
                id: 'post-13',
                type: 'post',
                platform: 'tiktok',
                author: 'lamentlove',
                name: 'Lyrics video trending',
                content: 'Cảm Ơn Người Đã Thức Cùng Tôi lyrics #fyp #xh',
                metrics: { mentions: 35, engagement: 6178, sentiment: 90 },
                children: [
                  { id: 'cmt-76', type: 'comment', author: 'karaoke.king', name: 'Karaoke King', content: 'Cảm ơn đã làm lyrics video, hát karaoke dễ hơn rồi 🎤', metrics: { engagement: 78, sentiment: 88 } },
                ],
              },
              {
                id: 'post-39',
                type: 'post',
                platform: 'tiktok',
                author: 'lyrics.aesthetic',
                name: 'Lyrics aesthetic Vpop 2026',
                content: 'Tổng hợp lyrics đẹp nhất Vpop 2026 - Những câu hát chạm đến trái tim #lyrics #vpop #aesthetic',
                metrics: { mentions: 2300, engagement: 67000, sentiment: 88 },
                children: [
                  { id: 'cmt-77', type: 'comment', author: 'quote.daily', name: 'Quote Daily', content: 'Save lại hết, mỗi câu đều hay quá 📝', metrics: { engagement: 456, sentiment: 92 } },
                  { id: 'cmt-78', type: 'comment', author: 'vpop.lover', name: 'Vpop Lover', content: 'Vpop 2026 chất lượng quá, tự hào nhạc Việt', metrics: { engagement: 890, sentiment: 95 } },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 'proj-4',
        type: 'project',
        name: 'TikTok Trends VN',
        description: 'Theo dõi xu hướng nổi bật trên TikTok Việt Nam',
        metrics: { mentions: 9600, engagement: 1100000, sentiment: 78, childCount: 3 },
        children: [
          {
            id: 'kw-10',
            type: 'keyword',
            name: '#fyp',
            metrics: { mentions: 12500, engagement: 580000, sentiment: 80, childCount: 450 },
            children: [
              {
                id: 'post-14',
                type: 'post',
                platform: 'tiktok',
                author: 'lamentlove',
                name: 'FYP trending music',
                content: 'Cảm Ơn Người Đã Thức Cùng Tôi #fyp #xh',
                metrics: { mentions: 35, engagement: 6178, sentiment: 92 },
                children: [],
              },
              {
                id: 'post-40',
                type: 'post',
                platform: 'tiktok',
                author: 'dance.crew.vn',
                name: 'Vũ đạo viral FYP',
                content: 'Thử thách vũ đạo mới đang viral trên FYP 🔥💃 #fyp #dance #challenge #viral',
                metrics: { mentions: 5600, engagement: 340000, sentiment: 85 },
                children: [
                  { id: 'cmt-79', type: 'comment', author: 'dancer.2004', name: 'Dancer 2004', content: 'Tutorial đi bạn ơi, muốn học quá!', metrics: { engagement: 1200, sentiment: 88 } },
                  { id: 'cmt-80', type: 'comment', author: 'awkward.dancer', name: 'Awkward Dancer', content: 'Người ta nhảy nhìn dễ vậy mà mình nhảy như con robot hỏng 😂', metrics: { engagement: 4500, sentiment: 75 } },
                  { id: 'cmt-81', type: 'comment', author: 'dance.teacher', name: 'Dance Teacher', content: 'Kỹ thuật tốt, nhưng cần giữ nhịp đều hơn ở đoạn bridge', metrics: { engagement: 234, sentiment: 72 } },
                ],
              },
              {
                id: 'post-41',
                type: 'post',
                platform: 'tiktok',
                author: 'food.hunter.vn',
                name: 'Quán phở ngon nhất Sài Gòn',
                content: 'Tìm được quán phở 40 năm tuổi ngon nhất Sài Gòn, xếp hàng 2 tiếng mới ăn được 🍜 #fyp #food #pho #saigon',
                metrics: { mentions: 3200, engagement: 189000, sentiment: 90 },
                children: [
                  { id: 'cmt-82', type: 'comment', author: 'foodie.sg', name: 'Foodie SG', content: 'Ở đâu vậy bạn ơi, tag địa chỉ đi 📍', metrics: { engagement: 2300, sentiment: 85 } },
                  { id: 'cmt-83', type: 'comment', author: 'pho.ha.noi', name: 'Phở Hà Nội', content: 'Phở Sài Gòn khác phở Hà Nội nhiều lắm, mỗi nơi một vị', metrics: { engagement: 890, sentiment: 70 } },
                  { id: 'cmt-84', type: 'comment', author: 'diet.fail', name: 'Diet Fail', content: 'Đang ăn kiêng mà xem cái này... thôi mai ăn kiêng lại vậy 😅', metrics: { engagement: 1560, sentiment: 80 } },
                  { id: 'cmt-85', type: 'comment', author: 'traveler.korea', name: 'Korean Traveler', content: 'Vietnamese pho is the best! I will visit this place 🇰🇷→🇻🇳', metrics: { engagement: 670, sentiment: 95 } },
                ],
              },
            ],
          },
          {
            id: 'kw-11',
            type: 'keyword',
            name: '#tiktoknews',
            metrics: { mentions: 5200, engagement: 420000, sentiment: 72, childCount: 180 },
            children: [
              {
                id: 'post-15',
                type: 'post',
                platform: 'tiktok',
                author: 'baohatinh',
                name: 'TikTok News Iran',
                content: 'Giây phút tên lửa Iran vượt qua lưới phòng không Israel #tiktoknews',
                metrics: { mentions: 3652, engagement: 145300, sentiment: 58 },
                children: [],
              },
              {
                id: 'post-42',
                type: 'post',
                platform: 'tiktok',
                author: 'tiktoknews.daily',
                name: 'TikTok cập nhật chính sách mới',
                content: 'TikTok thay đổi thuật toán: Creator dưới 10K follower sẽ được ưu tiên hiển thị #tiktoknews #creator #algorithm',
                metrics: { mentions: 7800, engagement: 234000, sentiment: 78 },
                children: [
                  { id: 'cmt-86', type: 'comment', author: 'small.creator', name: 'Small Creator', content: 'Cuối cùng cũng có cơ hội cho creator nhỏ rồi 🥹', metrics: { engagement: 3400, sentiment: 92 } },
                  { id: 'cmt-87', type: 'comment', author: 'big.creator.vn', name: 'Big Creator VN', content: 'Thay đổi này sẽ ảnh hưởng reach của creator lớn nhiều đây', metrics: { engagement: 890, sentiment: 45 } },
                ],
              },
            ],
          },
          {
            id: 'kw-12',
            type: 'keyword',
            name: '#xh',
            metrics: { mentions: 3800, engagement: 290000, sentiment: 78, childCount: 120 },
            children: [
              {
                id: 'post-43',
                type: 'post',
                platform: 'tiktok',
                author: 'comedy.vn.official',
                name: 'Hài Việt viral #xh',
                content: 'Khi bạn cố giải thích cho mẹ cách dùng smartphone 😂📱 #xh #hai #comedy #family',
                metrics: { mentions: 4500, engagement: 560000, sentiment: 90 },
                children: [
                  { id: 'cmt-88', type: 'comment', author: 'me.60.tuoi', name: 'Mẹ 60 Tuổi', content: 'Mẹ đây, mẹ biết dùng TikTok rồi nhé con 😤', metrics: { engagement: 12000, sentiment: 80 } },
                  { id: 'cmt-89', type: 'comment', author: 'relatable.vn', name: 'Relatable VN', content: 'Đúng mẹ mình luôn, giải thích 100 lần vẫn hỏi lại 😂', metrics: { engagement: 5600, sentiment: 85 } },
                  { id: 'cmt-90', type: 'comment', author: 'wholesome.content', name: 'Wholesome Content', content: 'Cute quá, thương mẹ ghê, kiên nhẫn dạy mẹ nha bạn ❤', metrics: { engagement: 3400, sentiment: 95 } },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 'proj-7',
        type: 'project',
        name: 'Phim Ảnh Hot',
        description: 'Theo dõi phim Việt và phim quốc tế đang hot trên MXH',
        metrics: { mentions: 14200, engagement: 1800000, sentiment: 80, childCount: 2 },
        children: [
          {
            id: 'kw-17',
            type: 'keyword',
            name: '#reviewphim',
            metrics: { mentions: 6800, engagement: 890000, sentiment: 78, childCount: 210 },
            children: [
              {
                id: 'post-44',
                type: 'post',
                platform: 'tiktok',
                author: 'review.phim.hay',
                name: 'Review phim Mai - Trấn Thành',
                content: 'Review phim MAI của Trấn Thành - Phim Việt hay nhất 2026? #reviewphim #mai #tranthanh #phimviet',
                metrics: { mentions: 8900, engagement: 456000, sentiment: 82 },
                children: [
                  { id: 'cmt-91', type: 'comment', author: 'cinephile.vn', name: 'Cinephile VN', content: 'Phim hay thật sự, Trấn Thành tiến bộ rất nhiều trong vai trò đạo diễn', metrics: { engagement: 2300, sentiment: 88 } },
                  { id: 'cmt-92', type: 'comment', author: 'anti.fan', name: 'Critic', content: 'Phim ổn nhưng chưa xứng "hay nhất", kịch bản vẫn còn lỗ hổng', metrics: { engagement: 1200, sentiment: 40 } },
                  { id: 'cmt-93', type: 'comment', author: 'khoc.het.nuoc.mat', name: 'Khóc Hết Nước Mắt', content: 'Xem xong khóc 3 ngày chưa hết, ai giống mình không 😭', metrics: { engagement: 4500, sentiment: 75 } },
                  { id: 'cmt-94', type: 'comment', author: 'phim.viet.fan', name: 'Phim Việt Fan', content: 'Ủng hộ phim Việt! Chất lượng ngày càng tốt hơn 🇻🇳🎬', metrics: { engagement: 890, sentiment: 92 } },
                ],
              },
              {
                id: 'post-45',
                type: 'post',
                platform: 'youtube',
                author: 'Movie Review VN',
                name: 'Top 10 phim hay nhất đầu 2026',
                content: 'TOP 10 PHIM HAY NHẤT ĐẦU NĂM 2026 mà bạn không nên bỏ lỡ #reviewphim #top10 #phimhay',
                metrics: { mentions: 3400, engagement: 123000, sentiment: 85 },
                children: [
                  { id: 'cmt-95', type: 'comment', author: 'movie.marathon', name: 'Movie Marathon', content: 'Cảm ơn đã tổng hợp, cuối tuần này coi hết luôn', metrics: { engagement: 234, sentiment: 88 } },
                  { id: 'cmt-96', type: 'comment', author: 'netflix.addict', name: 'Netflix Addict', content: 'Dune 3 phải #1 chứ, phim quá đỉnh', metrics: { engagement: 567, sentiment: 82 } },
                ],
              },
            ],
          },
          {
            id: 'kw-18',
            type: 'keyword',
            name: '#phimviet',
            metrics: { mentions: 5200, engagement: 670000, sentiment: 82, childCount: 150 },
            children: [
              {
                id: 'post-46',
                type: 'post',
                platform: 'facebook',
                author: 'Phim Việt Hay',
                name: 'Doanh thu phim Việt 2026',
                content: 'Phim Việt 2026 lập kỷ lục doanh thu: Tổng cộng hơn 2000 tỷ chỉ trong Q1 #phimviet #boxoffice',
                metrics: { mentions: 5600, engagement: 234000, sentiment: 88 },
                children: [
                  { id: 'cmt-97', type: 'comment', author: 'phim.industry', name: 'Phim Industry', content: 'Điện ảnh Việt đang ở thời kỳ vàng, chưa bao giờ thị trường tốt như vậy', metrics: { engagement: 890, sentiment: 92 } },
                  { id: 'cmt-98', type: 'comment', author: 'skeptic.viewer', name: 'Skeptic Viewer', content: 'Doanh thu cao nhưng chất lượng thì chưa đồng đều, vẫn nhiều phim dở', metrics: { engagement: 456, sentiment: 45 } },
                  { id: 'cmt-99', type: 'comment', author: 'dao.dien.tre', name: 'Đạo Diễn Trẻ', content: 'Thị trường phát triển = cơ hội cho filmmaker trẻ, mình đang rất hào hứng!', metrics: { engagement: 234, sentiment: 90 } },
                ],
              },
              {
                id: 'post-47',
                type: 'post',
                platform: 'tiktok',
                author: 'behind.the.scene',
                name: 'Hậu trường phim Việt',
                content: 'Hậu trường quay phim Việt: Diễn viên phải quay cảnh mưa lúc 3h sáng 🎬🌧️ #phimviet #hautruong #behindthescene',
                metrics: { mentions: 2300, engagement: 145000, sentiment: 80 },
                children: [
                  { id: 'cmt-100', type: 'comment', author: 'respect.actors', name: 'Respect Actors', content: 'Vất vả quá, respect diễn viên Việt Nam ❤', metrics: { engagement: 2300, sentiment: 90 } },
                  { id: 'cmt-101', type: 'comment', author: 'film.student', name: 'Film Student', content: 'Mình đang học điện ảnh, xem hậu trường học được rất nhiều', metrics: { engagement: 67, sentiment: 85 } },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'camp-3',
    type: 'campaign',
    name: 'Công nghệ & Sản phẩm',
    description: 'Theo dõi xu hướng công nghệ và review sản phẩm',
    metrics: { mentions: 15200, engagement: 1800000, sentiment: 74, childCount: 2 },
    children: [
      {
        id: 'proj-5',
        type: 'project',
        name: 'iPhone 17 Tracking',
        description: 'Theo dõi phản hồi về iPhone 17 Pro Max trên mạng xã hội',
        metrics: { mentions: 9800, engagement: 1200000, sentiment: 76, childCount: 2 },
        children: [
          {
            id: 'kw-13',
            type: 'keyword',
            name: 'iphone 17 promax',
            metrics: { mentions: 6200, engagement: 780000, sentiment: 78, childCount: 85 },
            children: [
              {
                id: 'post-16',
                type: 'post',
                platform: 'tiktok',
                author: 'tech_daily_vn',
                name: 'iPhone 17 Pro Max leak',
                content: 'Rò rỉ iPhone 17 Pro Max - thiết kế hoàn toàn mới #iphone17 #apple',
                metrics: { mentions: 2800, engagement: 42000, sentiment: 82 },
                children: [
                  { id: 'cmt-102', type: 'comment', author: 'apple.fan.boy', name: 'Apple Fan Boy', content: 'Thiết kế đỉnh quá, chắc chắn phải lên đời rồi 🍎', metrics: { engagement: 456, sentiment: 95 } },
                  { id: 'cmt-103', type: 'comment', author: 'android.forever', name: 'Android Forever', content: 'Vẫn thua Samsung S26 Ultra, Apple mỗi năm thay ít quá', metrics: { engagement: 890, sentiment: 30 } },
                  { id: 'cmt-104', type: 'comment', author: 'budget.phone', name: 'Budget Phone', content: 'Giá bao nhiêu vậy mọi người, chắc lại cả mớ tiền 💸', metrics: { engagement: 234, sentiment: 50 } },
                ],
              },
              {
                id: 'post-17',
                type: 'post',
                platform: 'youtube',
                author: 'TechReviewVN',
                name: 'So sánh iPhone 17 vs 16',
                content: 'So sánh chi tiết iPhone 17 Pro Max vs iPhone 16 Pro Max',
                metrics: { mentions: 1500, engagement: 18000, sentiment: 75 },
                children: [
                  { id: 'cmt-105', type: 'comment', author: 'tech.geek', name: 'Tech Geek', content: 'Camera upgrade đáng kể, còn lại thay đổi không nhiều', metrics: { engagement: 345, sentiment: 65 } },
                  { id: 'cmt-106', type: 'comment', author: 'iphone.16.user', name: 'iPhone 16 User', content: 'Đang xài 16 Pro Max vẫn ngon, chắc skip 17 lên 18 luôn', metrics: { engagement: 567, sentiment: 60 } },
                ],
              },
              {
                id: 'post-48',
                type: 'post',
                platform: 'tiktok',
                author: 'unbox.therapy.vn',
                name: 'Unbox iPhone 17 Pro Max đầu tiên tại VN',
                content: 'UNBOX iPhone 17 Pro Max ĐẦU TIÊN tại Việt Nam! Giá 38 triệu có đáng? #iphone17 #unbox #apple',
                metrics: { mentions: 6700, engagement: 345000, sentiment: 80 },
                children: [
                  { id: 'cmt-107', type: 'comment', author: 'giau.roi', name: 'Giàu Rồi', content: 'Mua ngay ngày đầu, không cần suy nghĩ 💰', metrics: { engagement: 234, sentiment: 85 } },
                  { id: 'cmt-108', type: 'comment', author: 'tin.nhan.gia', name: 'Tín Nhân Giả', content: '38 triệu mua được cả con xe Wave rồi, iPhone mắc quá', metrics: { engagement: 5600, sentiment: 35 } },
                  { id: 'cmt-109', type: 'comment', author: 'reviewer.pro', name: 'Reviewer Pro', content: 'Video unbox chuyên nghiệp, thông tin đầy đủ, cảm ơn bạn', metrics: { engagement: 890, sentiment: 82 } },
                  { id: 'cmt-110', type: 'comment', author: 'doi.giam.gia', name: 'Đợi Giảm Giá', content: 'Đợi 3 tháng nữa giá giảm rồi mua, không gấp đâu 😎', metrics: { engagement: 1200, sentiment: 65 } },
                ],
              },
            ],
          },
          {
            id: 'kw-14',
            type: 'keyword',
            name: '#apple',
            metrics: { mentions: 3600, engagement: 420000, sentiment: 74, childCount: 62 },
            children: [
              {
                id: 'post-18',
                type: 'post',
                platform: 'facebook',
                author: 'Apple Fan VN',
                name: 'Apple event 2026',
                content: 'Tổng hợp sự kiện Apple 2026 - iPhone 17 chính thức ra mắt',
                metrics: { mentions: 1800, engagement: 12000, sentiment: 80 },
                children: [
                  { id: 'cmt-111', type: 'comment', author: 'event.watcher', name: 'Event Watcher', content: 'Sự kiện năm nay ấn tượng nhất từ trước đến giờ, Tim Cook làm tốt lắm', metrics: { engagement: 345, sentiment: 88 } },
                  { id: 'cmt-112', type: 'comment', author: 'ai.enthusiast', name: 'AI Enthusiast', content: 'Apple Intelligence 2.0 mới là điểm nhấn, AI trên iPhone quá mạnh', metrics: { engagement: 890, sentiment: 90 } },
                ],
              },
              {
                id: 'post-49',
                type: 'post',
                platform: 'youtube',
                author: 'Apple Explained VN',
                name: 'Tất cả sản phẩm Apple 2026',
                content: 'TỔNG HỢP: Tất cả sản phẩm Apple ra mắt trong năm 2026 - MacBook M5, iPad Pro, Vision Pro 2 #apple #2026',
                metrics: { mentions: 3400, engagement: 89000, sentiment: 82 },
                children: [
                  { id: 'cmt-113', type: 'comment', author: 'macbook.user', name: 'MacBook User', content: 'MacBook M5 chip có đáng nâng cấp từ M3 không nhỉ?', metrics: { engagement: 234, sentiment: 70 } },
                  { id: 'cmt-114', type: 'comment', author: 'vision.pro.fan', name: 'Vision Pro Fan', content: 'Vision Pro 2 giảm giá và nhẹ hơn, đây mới là bản hoàn thiện', metrics: { engagement: 567, sentiment: 85 } },
                  { id: 'cmt-115', type: 'comment', author: 'hệ sinh thái', name: 'Apple Ecosystem', content: 'Hệ sinh thái Apple vẫn là lợi thế lớn nhất, dùng rồi khó bỏ', metrics: { engagement: 1200, sentiment: 80 } },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 'proj-6',
        type: 'project',
        name: 'VinFast Monitor',
        description: 'Theo dõi thương hiệu VinFast trên mạng xã hội',
        metrics: { mentions: 5400, engagement: 600000, sentiment: 72, childCount: 2 },
        children: [
          {
            id: 'kw-15',
            type: 'keyword',
            name: '#VinFast',
            metrics: { mentions: 3200, engagement: 380000, sentiment: 73, childCount: 110 },
            children: [
              {
                id: 'post-19',
                type: 'post',
                platform: 'tiktok',
                author: 'auto_review_vn',
                name: 'Review VF8 2026',
                content: 'Trải nghiệm thực tế VF8 sau 6 tháng sử dụng, có đáng mua?',
                metrics: { mentions: 2400, engagement: 18500, sentiment: 78 },
                children: [
                  { id: 'cmt-116', type: 'comment', author: 'vf8.owner', name: 'VF8 Owner', content: 'Mình đi được 20k km rồi, pin vẫn 95%, rất hài lòng', metrics: { engagement: 890, sentiment: 90 } },
                  { id: 'cmt-117', type: 'comment', author: 'xang.forever', name: 'Xăng Forever', content: 'Xe điện sạc lâu, đi xa bất tiện, mình vẫn thích xe xăng hơn', metrics: { engagement: 567, sentiment: 30 } },
                  { id: 'cmt-118', type: 'comment', author: 'green.energy', name: 'Green Energy', content: 'Xu hướng xe điện là tất yếu, VinFast đi đúng hướng', metrics: { engagement: 345, sentiment: 82 } },
                ],
              },
              {
                id: 'post-20',
                type: 'post',
                platform: 'facebook',
                author: 'VinFast Community',
                name: 'Hội VF8 Owners',
                content: 'Buổi giao lưu offline của các chủ xe VF8 tại Hà Nội',
                metrics: { mentions: 920, engagement: 5600, sentiment: 85 },
                children: [
                  { id: 'cmt-119', type: 'comment', author: 'community.vf', name: 'Community VF', content: 'Buổi giao lưu vui quá, hẹn gặp lại lần sau nha mọi người ❤', metrics: { engagement: 234, sentiment: 92 } },
                  { id: 'cmt-120', type: 'comment', author: 'sg.owner', name: 'SG Owner', content: 'Sài Gòn khi nào tổ chức vậy admin, mình cũng muốn tham gia', metrics: { engagement: 156, sentiment: 80 } },
                ],
              },
              {
                id: 'post-50',
                type: 'post',
                platform: 'tiktok',
                author: 'vinfast.official',
                name: 'VinFast VF3 - Xe điện mini giá rẻ',
                content: 'VinFast VF3 chính thức bán ra - Xe điện mini CHỈ TỪ 235 TRIỆU 🚗⚡ #VinFast #VF3 #xedien',
                metrics: { mentions: 12000, engagement: 890000, sentiment: 85 },
                children: [
                  { id: 'cmt-121', type: 'comment', author: 'first.car', name: 'First Car', content: 'Giá này sinh viên mới ra trường cũng mua được, tuyệt vời', metrics: { engagement: 4500, sentiment: 92 } },
                  { id: 'cmt-122', type: 'comment', author: 'xe.may.rider', name: 'Xe Máy Rider', content: 'Với giá này chuyển từ xe máy lên ô tô dễ dàng quá', metrics: { engagement: 2300, sentiment: 88 } },
                  { id: 'cmt-123', type: 'comment', author: 'safety.first', name: 'Safety First', content: 'Xe nhỏ vậy có an toàn không nhỉ? Ai có thông tin crash test share với', metrics: { engagement: 890, sentiment: 55 } },
                  { id: 'cmt-124', type: 'comment', author: 'viet.proud', name: 'Việt Proud', content: 'Tự hào xe Việt Nam, giá tốt chất lượng tốt 🇻🇳', metrics: { engagement: 6700, sentiment: 95 } },
                  { id: 'cmt-125', type: 'comment', author: 'compare.car', name: 'Compare Car', content: 'So với Wuling Mini EV thì VF3 hơn ở những điểm nào?', metrics: { engagement: 345, sentiment: 60 } },
                ],
              },
              {
                id: 'post-51',
                type: 'post',
                platform: 'youtube',
                author: 'Xế Cộng',
                name: 'VinFast xuất khẩu sang Mỹ',
                content: 'VinFast giao lô VF9 đầu tiên tại California: Phản hồi từ khách Mỹ ra sao? #VinFast #VF9 #xuatkhua',
                metrics: { mentions: 5600, engagement: 234000, sentiment: 75 },
                children: [
                  { id: 'cmt-126', type: 'comment', author: 'oversea.viet', name: 'Overseas Viet', content: 'Mình ở Cali, thấy VF9 chạy ngoài đường rồi, đẹp lắm', metrics: { engagement: 2300, sentiment: 88 } },
                  { id: 'cmt-127', type: 'comment', author: 'stock.trader', name: 'Stock Trader', content: 'VFS stock lên ngay sau tin này, đã mua từ lâu 📈', metrics: { engagement: 890, sentiment: 82 } },
                  { id: 'cmt-128', type: 'comment', author: 'realistic.view', name: 'Realistic View', content: 'Phải chờ xem doanh số thực tế, giao xe ≠ thành công', metrics: { engagement: 456, sentiment: 50 } },
                ],
              },
            ],
          },
          {
            id: 'kw-16',
            type: 'keyword',
            name: '#VF8',
            metrics: { mentions: 2200, engagement: 220000, sentiment: 70, childCount: 45 },
            children: [
              {
                id: 'post-21',
                type: 'post',
                platform: 'youtube',
                author: 'TechAutoVN',
                name: 'VF8 vs BYD Atto 3',
                content: 'Video so sánh chi tiết giữa VinFast VF8 và BYD Atto 3',
                metrics: { mentions: 1800, engagement: 12300, sentiment: 68 },
                children: [
                  { id: 'cmt-129', type: 'comment', author: 'byd.fan', name: 'BYD Fan', content: 'BYD pin LFP bền hơn, công nghệ Trung Quốc không thua kém đâu', metrics: { engagement: 345, sentiment: 55 } },
                  { id: 'cmt-130', type: 'comment', author: 'vinfast.supporter', name: 'VinFast Supporter', content: 'Ủng hộ hàng Việt, VF8 thiết kế đẹp hơn hẳn', metrics: { engagement: 890, sentiment: 80 } },
                  { id: 'cmt-131', type: 'comment', author: 'fair.review', name: 'Fair Review', content: 'Mỗi xe một ưu nhược riêng, video so sánh khách quan, cảm ơn', metrics: { engagement: 234, sentiment: 72 } },
                ],
              },
              {
                id: 'post-52',
                type: 'post',
                platform: 'facebook',
                author: 'Hội VF8 Việt Nam',
                name: 'Lỗi phần mềm VF8 và cách khắc phục',
                content: 'TỔNG HỢP các lỗi phần mềm VF8 thường gặp và cách khắc phục - Update OTA tháng 3/2026 #VF8 #VinFast',
                metrics: { mentions: 3400, engagement: 45000, sentiment: 55 },
                children: [
                  { id: 'cmt-132', type: 'comment', author: 'vf8.it.guy', name: 'VF8 IT Guy', content: 'Update OTA lần này fix được lỗi màn hình, cuối cùng cũng xong', metrics: { engagement: 567, sentiment: 75 } },
                  { id: 'cmt-133', type: 'comment', author: 'moi.mua.xe', name: 'Mới Mua Xe', content: 'Mình mới mua, chưa gặp lỗi gì, có lẽ bản mới đã fix hết?', metrics: { engagement: 123, sentiment: 78 } },
                  { id: 'cmt-134', type: 'comment', author: 'frustrated.owner', name: 'Frustrated Owner', content: 'Lỗi điều hòa vẫn chưa fix, nóng muốn chết trong xe 😤', metrics: { engagement: 1200, sentiment: 18 } },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 'proj-8',
        type: 'project',
        name: 'AI & ChatGPT',
        description: 'Theo dõi xu hướng AI và ChatGPT trên MXH Việt Nam',
        metrics: { mentions: 18500, engagement: 2300000, sentiment: 78, childCount: 3 },
        children: [
          {
            id: 'kw-19',
            type: 'keyword',
            name: '#AI',
            metrics: { mentions: 9200, engagement: 1200000, sentiment: 76, childCount: 280 },
            children: [
              {
                id: 'post-53',
                type: 'post',
                platform: 'tiktok',
                author: 'ai.explained.vn',
                name: 'AI thay thế lập trình viên?',
                content: 'AI có thay thế lập trình viên không? Câu trả lời sẽ khiến bạn bất ngờ #AI #laptrinhvien #congnghe',
                metrics: { mentions: 5600, engagement: 345000, sentiment: 65 },
                children: [
                  { id: 'cmt-135', type: 'comment', author: 'dev.senior', name: 'Dev Senior', content: 'AI là công cụ hỗ trợ, không thay thế được tư duy giải quyết vấn đề', metrics: { engagement: 2300, sentiment: 70 } },
                  { id: 'cmt-136', type: 'comment', author: 'sv.it.hcm', name: 'SV IT HCM', content: 'Em đang học IT, nghe tin này lo quá, có nên chuyển ngành không? 😰', metrics: { engagement: 4500, sentiment: 30 } },
                  { id: 'cmt-137', type: 'comment', author: 'ai.researcher', name: 'AI Researcher', content: 'AI hiện tại vẫn cần người giám sát, ít nhất 10 năm nữa mới thay thế được', metrics: { engagement: 890, sentiment: 68 } },
                  { id: 'cmt-138', type: 'comment', author: 'chill.dev', name: 'Chill Dev', content: 'Thay thế thì mình chuyển sang dạy AI code cho đúng 😂', metrics: { engagement: 6700, sentiment: 80 } },
                ],
              },
              {
                id: 'post-54',
                type: 'post',
                platform: 'youtube',
                author: 'Viet Tech',
                name: 'Ứng dụng AI trong cuộc sống hàng ngày',
                content: '10 ỨNG DỤNG AI bạn nên sử dụng hàng ngày để tăng năng suất gấp 10 lần #AI #productivity #congnghe',
                metrics: { mentions: 3400, engagement: 178000, sentiment: 82 },
                children: [
                  { id: 'cmt-139', type: 'comment', author: 'productivity.guru', name: 'Productivity Guru', content: 'Notion AI + ChatGPT combo quá mạnh, công việc mình nhanh hơn 3x', metrics: { engagement: 1200, sentiment: 90 } },
                  { id: 'cmt-140', type: 'comment', author: 'lazy.worker', name: 'Lazy Worker', content: 'Dùng AI xong rảnh quá không biết làm gì 😂', metrics: { engagement: 3400, sentiment: 85 } },
                ],
              },
            ],
          },
          {
            id: 'kw-20',
            type: 'keyword',
            name: '#ChatGPT',
            metrics: { mentions: 6800, engagement: 780000, sentiment: 80, childCount: 190 },
            children: [
              {
                id: 'post-55',
                type: 'post',
                platform: 'tiktok',
                author: 'chatgpt.tips.vn',
                name: 'Prompt ChatGPT hay nhất 2026',
                content: '5 prompt ChatGPT thần thánh giúp bạn viết content x10 tốc độ #ChatGPT #prompt #content #tips',
                metrics: { mentions: 8900, engagement: 456000, sentiment: 88 },
                children: [
                  { id: 'cmt-141', type: 'comment', author: 'content.creator', name: 'Content Creator', content: 'Save ngay, prompt #3 cực kỳ hữu ích cho viết blog', metrics: { engagement: 2300, sentiment: 92 } },
                  { id: 'cmt-142', type: 'comment', author: 'writer.oldschool', name: 'Writer Oldschool', content: 'Viết bằng AI thì mất đi cá tính riêng, mình vẫn thích tự viết', metrics: { engagement: 890, sentiment: 45 } },
                  { id: 'cmt-143', type: 'comment', author: 'marketer.digital', name: 'Digital Marketer', content: 'Dùng prompt này cho email marketing, tỷ lệ mở tăng 40%!', metrics: { engagement: 567, sentiment: 90 } },
                ],
              },
              {
                id: 'post-56',
                type: 'post',
                platform: 'facebook',
                author: 'GPT Vietnam Community',
                name: 'So sánh ChatGPT vs Claude vs Gemini',
                content: 'SO SÁNH CHI TIẾT: ChatGPT-5 vs Claude 4 vs Gemini 2.0 - AI nào đỉnh nhất 2026? #ChatGPT #Claude #Gemini',
                metrics: { mentions: 6700, engagement: 345000, sentiment: 75 },
                children: [
                  { id: 'cmt-144', type: 'comment', author: 'claude.fan', name: 'Claude Fan', content: 'Claude 4 viết code đỉnh nhất, ChatGPT tốt cho sáng tạo, Gemini mạnh tìm kiếm', metrics: { engagement: 3400, sentiment: 82 } },
                  { id: 'cmt-145', type: 'comment', author: 'chatgpt.stan', name: 'ChatGPT Stan', content: 'ChatGPT vẫn số 1, ecosystem và plugin phong phú nhất', metrics: { engagement: 2300, sentiment: 85 } },
                  { id: 'cmt-146', type: 'comment', author: 'neutral.reviewer', name: 'Neutral Reviewer', content: 'Mỗi AI một thế mạnh, tùy mục đích sử dụng mà chọn', metrics: { engagement: 1200, sentiment: 70 } },
                  { id: 'cmt-147', type: 'comment', author: 'open.source.fan', name: 'Open Source Fan', content: 'Llama 4 cũng rất tốt và miễn phí, đừng quên open source', metrics: { engagement: 567, sentiment: 75 } },
                ],
              },
            ],
          },
          {
            id: 'kw-21',
            type: 'keyword',
            name: '#congnghe2026',
            metrics: { mentions: 4500, engagement: 450000, sentiment: 78, childCount: 120 },
            children: [
              {
                id: 'post-57',
                type: 'post',
                platform: 'tiktok',
                author: 'tech.trend.vn',
                name: 'Xu hướng công nghệ 2026',
                content: '5 xu hướng công nghệ sẽ THAY ĐỔI cuộc sống bạn trong 2026 #congnghe2026 #tech #trend',
                metrics: { mentions: 3400, engagement: 189000, sentiment: 80 },
                children: [
                  { id: 'cmt-148', type: 'comment', author: 'future.is.now', name: 'Future Is Now', content: 'Spatial computing sẽ bùng nổ, Apple Vision Pro 2 là bước ngoặt', metrics: { engagement: 456, sentiment: 85 } },
                  { id: 'cmt-149', type: 'comment', author: 'skeptic.tech', name: 'Skeptic Tech', content: 'Năm nào cũng nói "thay đổi cuộc sống" mà cuối cùng vẫn lướt TikTok 😂', metrics: { engagement: 3400, sentiment: 65 } },
                  { id: 'cmt-150', type: 'comment', author: 'startup.founder', name: 'Startup Founder', content: 'Đang xây startup về AI agent, đúng xu hướng rồi 🚀', metrics: { engagement: 234, sentiment: 88 } },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'camp-4',
    type: 'campaign',
    name: 'Thể thao & Esports',
    description: 'Theo dõi tin tức thể thao và esports trên MXH',
    metrics: { mentions: 22000, engagement: 2800000, sentiment: 80, childCount: 2 },
    children: [
      {
        id: 'proj-9',
        type: 'project',
        name: 'Bóng đá Việt Nam',
        description: 'Theo dõi đội tuyển Việt Nam và V-League',
        metrics: { mentions: 14500, engagement: 1900000, sentiment: 78, childCount: 2 },
        children: [
          {
            id: 'kw-22',
            type: 'keyword',
            name: '#doituyenvietnam',
            metrics: { mentions: 8900, engagement: 1200000, sentiment: 80, childCount: 320 },
            children: [
              {
                id: 'post-58',
                type: 'post',
                platform: 'tiktok',
                author: 'bongda.360',
                name: 'Việt Nam vs Thái Lan highlights',
                content: 'HIGHLIGHTS: Việt Nam 3-1 Thái Lan - Chiến thắng lịch sử tại AFF Cup 2026! 🇻🇳⚽ #doituyenvietnam #affcup #vietnam',
                metrics: { mentions: 15000, engagement: 890000, sentiment: 95 },
                children: [
                  { id: 'cmt-151', type: 'comment', author: 'fan.bong.da', name: 'Fan Bóng Đá', content: 'VIỆT NAM VÔ ĐỊCH! Bàn thắng của Quang Hải đẹp quá 🔥🔥🔥', metrics: { engagement: 12000, sentiment: 98 } },
                  { id: 'cmt-152', type: 'comment', author: 'thai.fan', name: 'Thai Fan VN', content: 'GG Việt Nam, trận này xứng đáng thắng', metrics: { engagement: 3400, sentiment: 70 } },
                  { id: 'cmt-153', type: 'comment', author: 'hlv.sofa', name: 'HLV Sofa', content: 'Chiến thuật của HLV Kim Sang-sik quá xuất sắc, pressing hiệu quả', metrics: { engagement: 2300, sentiment: 90 } },
                  { id: 'cmt-154', type: 'comment', author: 'xuong.duong', name: 'Xuống Đường', content: 'Ai ở Sài Gòn đi bão không, hẹn Nguyễn Huệ nhé 🏍️🎉', metrics: { engagement: 8900, sentiment: 95 } },
                  { id: 'cmt-155', type: 'comment', author: 'nu.fan.bongda', name: 'Nữ Fan Bóng Đá', content: 'Lần đầu xem bóng đá mà khóc vì vui, tự hào Việt Nam quá ❤', metrics: { engagement: 5600, sentiment: 96 } },
                ],
              },
              {
                id: 'post-59',
                type: 'post',
                platform: 'youtube',
                author: 'VFF Channel',
                name: 'Họp báo sau trận VN vs Thái',
                content: 'HỌP BÁO: HLV Kim Sang-sik chia sẻ sau chiến thắng 3-1 trước Thái Lan #doituyenvietnam',
                metrics: { mentions: 3400, engagement: 89000, sentiment: 85 },
                children: [
                  { id: 'cmt-156', type: 'comment', author: 'hlv.respect', name: 'Respect HLV', content: 'Thầy Kim nói chuyện khiêm tốn quá, huấn luyện giỏi mà không kiêu', metrics: { engagement: 890, sentiment: 90 } },
                  { id: 'cmt-157', type: 'comment', author: 'tactical.analyst', name: 'Tactical Analyst', content: 'Thầy Kim chia sẻ rất chi tiết về chiến thuật, học hỏi được nhiều', metrics: { engagement: 345, sentiment: 82 } },
                ],
              },
              {
                id: 'post-60',
                type: 'post',
                platform: 'facebook',
                author: 'Bóng Đá Plus',
                name: 'Quang Hải - Ngôi sao AFF Cup',
                content: 'Quang Hải - Ngôi sao sáng nhất AFF Cup 2026: 5 bàn thắng, 3 kiến tạo #doituyenvietnam #quanghai',
                metrics: { mentions: 6700, engagement: 345000, sentiment: 92 },
                children: [
                  { id: 'cmt-158', type: 'comment', author: 'qh19.fan', name: 'QH19 Fan', content: 'Quang Hải trở lại phong độ đỉnh cao, xứng đáng Quả bóng vàng', metrics: { engagement: 4500, sentiment: 95 } },
                  { id: 'cmt-159', type: 'comment', author: 'football.stats', name: 'Football Stats', content: '5 bàn 3 kiến tạo, hiệu suất tốt nhất giải, không ai bàn cãi được', metrics: { engagement: 1200, sentiment: 88 } },
                ],
              },
            ],
          },
          {
            id: 'kw-23',
            type: 'keyword',
            name: '#vleague',
            metrics: { mentions: 5600, engagement: 670000, sentiment: 72, childCount: 180 },
            children: [
              {
                id: 'post-61',
                type: 'post',
                platform: 'tiktok',
                author: 'vleague.daily',
                name: 'Bàn thắng đẹp nhất vòng 10',
                content: 'TOP 5 bàn thắng đẹp nhất vòng 10 V-League 2026 ⚽🔥 #vleague #banthang #top5',
                metrics: { mentions: 2300, engagement: 89000, sentiment: 85 },
                children: [
                  { id: 'cmt-160', type: 'comment', author: 'hagl.fan', name: 'HAGL Fan', content: 'Bàn của Văn Toàn phải #1, kỹ thuật quá đỉnh', metrics: { engagement: 890, sentiment: 90 } },
                  { id: 'cmt-161', type: 'comment', author: 'hn.fc.fan', name: 'Hà Nội FC Fan', content: 'Hà Nội FC đang dẫn đầu BXH, năm nay vô địch chắc rồi 🏆', metrics: { engagement: 567, sentiment: 88 } },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 'proj-10',
        type: 'project',
        name: 'Esports Vietnam',
        description: 'Theo dõi tin tức esports và gaming tại Việt Nam',
        metrics: { mentions: 7500, engagement: 900000, sentiment: 82, childCount: 2 },
        children: [
          {
            id: 'kw-24',
            type: 'keyword',
            name: '#esportsvn',
            metrics: { mentions: 4200, engagement: 560000, sentiment: 84, childCount: 150 },
            children: [
              {
                id: 'post-62',
                type: 'post',
                platform: 'tiktok',
                author: 'esports.vn',
                name: 'GAM vô địch VCS Spring 2026',
                content: 'GAM Esports VÔ ĐỊCH VCS Spring 2026! Sweep 3-0 trước Team Flash 🏆🎮 #esportsvn #vcs #gam #leagueoflegends',
                metrics: { mentions: 5600, engagement: 340000, sentiment: 92 },
                children: [
                  { id: 'cmt-162', type: 'comment', author: 'gam.fan.1', name: 'GAM Fan #1', content: 'GAM ĐỈNH QUÁ! Levi carry cả giải luôn 🐯', metrics: { engagement: 4500, sentiment: 98 } },
                  { id: 'cmt-163', type: 'comment', author: 'tf.fan.sad', name: 'TF Fan Sad', content: 'Team Flash cố lên, mùa sau sẽ khác 😢', metrics: { engagement: 1200, sentiment: 35 } },
                  { id: 'cmt-164', type: 'comment', author: 'worlds.hope', name: 'Worlds Hope', content: 'Hy vọng GAM đi xa tại Worlds năm nay, VCS cần một kỳ tích', metrics: { engagement: 2300, sentiment: 80 } },
                  { id: 'cmt-165', type: 'comment', author: 'casual.gamer', name: 'Casual Gamer', content: 'Trận chung kết hay quá, xem không rời mắt được', metrics: { engagement: 890, sentiment: 88 } },
                ],
              },
              {
                id: 'post-63',
                type: 'post',
                platform: 'youtube',
                author: 'Vietnam Esports',
                name: 'Highlight VCS Spring Finals',
                content: 'FULL HIGHLIGHTS VCS Spring 2026 Finals: GAM vs Team Flash - Series kinh điển #esportsvn #vcs',
                metrics: { mentions: 2300, engagement: 123000, sentiment: 88 },
                children: [
                  { id: 'cmt-166', type: 'comment', author: 'play.by.play', name: 'Play by Play', content: 'Game 2 là trận hay nhất VCS lịch sử, teamfight 50 phút quá căng', metrics: { engagement: 567, sentiment: 90 } },
                ],
              },
            ],
          },
          {
            id: 'kw-25',
            type: 'keyword',
            name: '#gaming',
            metrics: { mentions: 3300, engagement: 340000, sentiment: 80, childCount: 95 },
            children: [
              {
                id: 'post-64',
                type: 'post',
                platform: 'tiktok',
                author: 'gaming.vn.tips',
                name: 'GTA 6 chính thức ra mắt',
                content: 'GTA 6 CHÍNH THỨC RA MẮT! Review nhanh sau 24h chơi - Có xứng đáng chờ đợi? #gaming #gta6 #review',
                metrics: { mentions: 12000, engagement: 670000, sentiment: 85 },
                children: [
                  { id: 'cmt-167', type: 'comment', author: 'gta.veteran', name: 'GTA Veteran', content: 'Chờ 13 năm, cuối cùng GTA 6 cũng ra, đồ họa đẹp ngoài sức tưởng tượng 😭', metrics: { engagement: 6700, sentiment: 95 } },
                  { id: 'cmt-168', type: 'comment', author: 'pc.potato', name: 'PC Potato', content: 'Máy mình chắc không chạy nổi, ai cho mượn PS6 với 😅', metrics: { engagement: 4500, sentiment: 65 } },
                  { id: 'cmt-169', type: 'comment', author: 'rockstar.fan', name: 'Rockstar Fan', content: 'Map Vice City rộng gấp 3 lần GTA 5, chi tiết không tưởng', metrics: { engagement: 2300, sentiment: 92 } },
                  { id: 'cmt-170', type: 'comment', author: 'parent.gamer', name: 'Parent Gamer', content: 'Con mình xin mua, mà game 18+ thì sao cho chơi được 🤔', metrics: { engagement: 890, sentiment: 55 } },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'camp-5',
    type: 'campaign',
    name: 'Giáo dục & Đời sống',
    description: 'Theo dõi xu hướng giáo dục, tuyển sinh và đời sống giới trẻ',
    metrics: { mentions: 16800, engagement: 1500000, sentiment: 75, childCount: 2 },
    children: [
      {
        id: 'proj-11',
        type: 'project',
        name: 'Tuyển sinh 2026',
        description: 'Theo dõi mùa tuyển sinh đại học 2026',
        metrics: { mentions: 9200, engagement: 800000, sentiment: 70, childCount: 2 },
        children: [
          {
            id: 'kw-26',
            type: 'keyword',
            name: '#tuyensinh2026',
            metrics: { mentions: 5800, engagement: 450000, sentiment: 68, childCount: 200 },
            children: [
              {
                id: 'post-65',
                type: 'post',
                platform: 'tiktok',
                author: 'huong.nghiep.360',
                name: 'Top ngành học hot nhất 2026',
                content: 'TOP 10 ngành học HOT NHẤT 2026: AI, Data Science dẫn đầu, Y dược vẫn top 3 #tuyensinh2026 #nganhhoc #daihoc',
                metrics: { mentions: 4500, engagement: 234000, sentiment: 75 },
                children: [
                  { id: 'cmt-171', type: 'comment', author: 'hocsinh.12', name: 'Học Sinh 12', content: 'Em đang phân vân giữa CNTT và Kinh tế, ai tư vấn giúp em với 🥺', metrics: { engagement: 2300, sentiment: 50 } },
                  { id: 'cmt-172', type: 'comment', author: 'it.graduate', name: 'IT Graduate', content: 'Học IT đi em, ra trường lương khởi điểm 15-20 triệu', metrics: { engagement: 890, sentiment: 82 } },
                  { id: 'cmt-173', type: 'comment', author: 'bac.si.tre', name: 'Bác Sĩ Trẻ', content: 'Y khoa học 6 năm vất vả nhưng nghề rất ổn định và ý nghĩa', metrics: { engagement: 567, sentiment: 78 } },
                  { id: 'cmt-174', type: 'comment', author: 'phu.huynh.lo', name: 'Phụ Huynh Lo', content: 'Con mình muốn học nghệ thuật, mình không biết có nên ủng hộ không', metrics: { engagement: 1200, sentiment: 45 } },
                ],
              },
              {
                id: 'post-66',
                type: 'post',
                platform: 'facebook',
                author: 'Bộ GD&ĐT',
                name: 'Thay đổi quy chế tuyển sinh 2026',
                content: 'CHÍNH THỨC: Bộ GD&ĐT công bố thay đổi quy chế tuyển sinh đại học 2026 - Thêm phương thức xét tuyển mới #tuyensinh2026',
                metrics: { mentions: 8900, engagement: 456000, sentiment: 60 },
                children: [
                  { id: 'cmt-175', type: 'comment', author: 'giao.vien.12', name: 'Giáo Viên 12', content: 'Thay đổi liên tục, cả thầy cả trò đều stress', metrics: { engagement: 3400, sentiment: 30 } },
                  { id: 'cmt-176', type: 'comment', author: 'phu.huynh.hn', name: 'Phụ Huynh HN', content: 'Mong Bộ có hướng dẫn chi tiết hơn, nhiều phụ huynh đọc không hiểu', metrics: { engagement: 2300, sentiment: 40 } },
                  { id: 'cmt-177', type: 'comment', author: 'tuyen.sinh.expert', name: 'Tuyển Sinh Expert', content: 'Phương thức mới tạo nhiều cơ hội hơn cho học sinh, hướng đi đúng', metrics: { engagement: 890, sentiment: 75 } },
                ],
              },
            ],
          },
          {
            id: 'kw-27',
            type: 'keyword',
            name: '#thitotnghi',
            metrics: { mentions: 3400, engagement: 350000, sentiment: 65, childCount: 150 },
            children: [
              {
                id: 'post-67',
                type: 'post',
                platform: 'tiktok',
                author: 'onthi.tips',
                name: 'Mẹo ôn thi tốt nghiệp 2026',
                content: '10 MẸO ÔN THI TỐT NGHIỆP 2026 hiệu quả nhất - Đỗ đại học như ý muốn #thitotnghi #onthi #tips',
                metrics: { mentions: 2300, engagement: 145000, sentiment: 78 },
                children: [
                  { id: 'cmt-178', type: 'comment', author: 'lop12.stress', name: 'Lớp 12 Stress', content: 'Cảm ơn nhiều ạ, đang áp lực kinh khủng, xem xong thấy bình tĩnh hơn', metrics: { engagement: 4500, sentiment: 65 } },
                  { id: 'cmt-179', type: 'comment', author: 'da.do.dh', name: 'Đã Đỗ ĐH', content: 'Áp dụng mẹo #3 và #7 năm ngoái, đỗ ĐH Bách Khoa luôn, tin mình đi', metrics: { engagement: 2300, sentiment: 90 } },
                  { id: 'cmt-180', type: 'comment', author: 'me.lo.con', name: 'Mẹ Lo Con', content: 'Chuyển cho con xem ngay, cảm ơn bạn trẻ ❤', metrics: { engagement: 890, sentiment: 82 } },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 'proj-12',
        type: 'project',
        name: 'Đời Sống Gen Z',
        description: 'Theo dõi xu hướng và thảo luận về đời sống giới trẻ',
        metrics: { mentions: 7600, engagement: 700000, sentiment: 80, childCount: 2 },
        children: [
          {
            id: 'kw-28',
            type: 'keyword',
            name: '#genz',
            metrics: { mentions: 4500, engagement: 420000, sentiment: 82, childCount: 180 },
            children: [
              {
                id: 'post-68',
                type: 'post',
                platform: 'tiktok',
                author: 'genz.life.vn',
                name: 'Gen Z và áp lực thành công',
                content: 'Gen Z đang kiệt sức: Áp lực thành công sớm từ MXH có đang hủy hoại giới trẻ? #genz #apluc #mentalhealth',
                metrics: { mentions: 5600, engagement: 345000, sentiment: 55 },
                children: [
                  { id: 'cmt-181', type: 'comment', author: 'gen.z.2003', name: 'GenZ 2003', content: 'Đúng quá, cứ lướt TikTok thấy ai cũng thành công mà mình thì không, stress kinh khủng', metrics: { engagement: 6700, sentiment: 25 } },
                  { id: 'cmt-182', type: 'comment', author: 'tam.ly.hoc', name: 'Tâm Lý Học', content: 'Đây gọi là "comparison trap", cần hạn chế thời gian dùng MXH', metrics: { engagement: 2300, sentiment: 70 } },
                  { id: 'cmt-183', type: 'comment', author: 'chill.life', name: 'Chill Life', content: 'Sống chậm lại, không ai bắt mình phải thành công lúc 20 tuổi cả', metrics: { engagement: 4500, sentiment: 80 } },
                  { id: 'cmt-184', type: 'comment', author: 'motivational.speaker', name: 'Motivational Speaker', content: 'Thành công không có deadline, mỗi người có timeline riêng ❤', metrics: { engagement: 8900, sentiment: 85 } },
                ],
              },
              {
                id: 'post-69',
                type: 'post',
                platform: 'facebook',
                author: 'Kenh14',
                name: 'Gen Z chi tiêu như thế nào',
                content: 'Khảo sát: Gen Z Việt Nam chi 40% thu nhập cho ăn uống và giải trí, chỉ 15% cho tiết kiệm #genz #chitieu #taichinh',
                metrics: { mentions: 4500, engagement: 234000, sentiment: 60 },
                children: [
                  { id: 'cmt-185', type: 'comment', author: 'financial.advisor', name: 'Financial Advisor', content: 'Nên dành ít nhất 20% cho tiết kiệm, 40% cho ăn uống là quá nhiều', metrics: { engagement: 2300, sentiment: 55 } },
                  { id: 'cmt-186', type: 'comment', author: 'yolo.life', name: 'YOLO Life', content: 'Sống 1 lần thôi, tiết kiệm cũng không mua nổi nhà đâu 😂', metrics: { engagement: 5600, sentiment: 70 } },
                  { id: 'cmt-187', type: 'comment', author: 'save.money.tips', name: 'Save Money Tips', content: 'Mình cũng GenZ nhưng tiết kiệm 30%, quan trọng là biết cách quản lý', metrics: { engagement: 890, sentiment: 78 } },
                ],
              },
            ],
          },
          {
            id: 'kw-29',
            type: 'keyword',
            name: '#mentalhealth',
            metrics: { mentions: 3100, engagement: 280000, sentiment: 65, childCount: 95 },
            children: [
              {
                id: 'post-70',
                type: 'post',
                platform: 'tiktok',
                author: 'mental.health.vn',
                name: 'Dấu hiệu burnout ở người trẻ',
                content: '5 dấu hiệu bạn đang BURNOUT mà không biết - Và cách phục hồi #mentalhealth #burnout #selfcare',
                metrics: { mentions: 3400, engagement: 189000, sentiment: 60 },
                children: [
                  { id: 'cmt-188', type: 'comment', author: 'burnout.real', name: 'Burnout Real', content: 'Check hết 5/5 dấu hiệu... có lẽ mình cần nghỉ ngơi thật rồi 😔', metrics: { engagement: 4500, sentiment: 25 } },
                  { id: 'cmt-189', type: 'comment', author: 'psychologist.vn', name: 'Psychologist VN', content: 'Video rất hữu ích, nhưng nếu nghiêm trọng nên gặp chuyên gia nhé', metrics: { engagement: 1200, sentiment: 72 } },
                  { id: 'cmt-190', type: 'comment', author: 'recovery.journey', name: 'Recovery Journey', content: 'Mình từng burnout nặng, nghỉ việc 3 tháng mới hồi phục, đừng coi thường', metrics: { engagement: 2300, sentiment: 55 } },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
