export type EntityType = 'campaign' | 'project' | 'keyword' | 'post' | 'comment';

export type PlatformType = 'tiktok' | 'facebook' | 'youtube';

export interface HeapNode {
  id: string;
  type: EntityType;
  name: string;
  description?: string;
  platform?: PlatformType;
  author?: string;
  content?: string;
  metrics: {
    mentions?: number;
    engagement?: number;
    sentiment?: number;
    childCount?: number;
  };
  children?: HeapNode[];

  // Phase 1 — enriched fields (auto-generated by enrichMockData)
  mentionVelocity?: number;       // mentions/hour (recent 2h window)
  trendDirection?: 'up' | 'down' | 'stable';
  trendData?: number[];           // 7 data points for sparkline
  isCrisis?: boolean;             // sentiment drop > 15% in 2h or sentiment < 30 + high velocity
}

export interface PhysicsState {
  baseX: number;
  baseY: number;
  oscFreqX: number;
  oscFreqY: number;
  oscAmpX: number;
  oscAmpY: number;
  phaseX: number;
  phaseY: number;
}

export interface SatelliteData extends HeapNode {
  parentId: string;
  satIndex: number;
  satTotal: number;
}
