/**
 * Platform-native post tooltip data types.
 * These extend the base HeapNode with platform-specific fields
 * generated by enrichPostData().
 */

export type PostPlatform = 'facebook' | 'tiktok' | 'youtube' | 'x' | 'instagram' | 'news' | 'forum';

export interface PostData {
  id: string;
  platform: PostPlatform;
  url: string;
  content: string;
  authorName: string;
  authorHandle?: string;
  authorAvatarUrl?: string;
  publishedAt: Date;
  sentiment: number;
  thumbnailUrl?: string;
  mediaType?: 'image' | 'video' | 'link' | 'text';
  likes: number;
  comments: number;
  shares: number;
  platformData?: Record<string, unknown>;
}

/* ── Facebook ── */

export interface FacebookReactions {
  like: number;
  love: number;
  haha: number;
  wow: number;
  sad: number;
  angry: number;
}

export interface FacebookPostData extends PostData {
  platform: 'facebook';
  platformData: {
    reactions: FacebookReactions;
    isVerified?: boolean;
    pageCategory?: string;
    imageCount?: number;
  };
}

/* ── TikTok ── */

export interface TikTokPostData extends PostData {
  platform: 'tiktok';
  mediaType: 'video';
  platformData: {
    videoDuration?: number;
    musicName?: string;
    musicAuthor?: string;
    hashtags: string[];
    views: number;
    bookmarks?: number;
  };
}

/* ── YouTube ── */

export interface YouTubePostData extends PostData {
  platform: 'youtube';
  mediaType: 'video';
  platformData: {
    videoId: string;
    duration: string;
    views: number;
    channelName: string;
    channelSubscribers?: string;
    isShort?: boolean;
  };
}
