apiVersion: v1
kind: ConfigMap
metadata:
  name: smap-web-config
  namespace: smap
  labels:
    app: smap-web
    component: frontend
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  PORT: "5000"
  HOSTNAME: "0.0.0.0"
  # NEXT_PUBLIC_HOSTNAME: "https://smap-api.tantai.dev/identity"  # Uncomment and set your API URL
